- param: file
  title: Generated file name
  type: textfield
  example: ex. script

- param: greeting
  title: Preffered greeting?
  type: choice
  options:
    - Hello
    - Greetings
    - What's up
- param: name
  title: Your name
  type: textfield
  example: Alex